// Image demonstrates the raster-image embedding pipeline. To keep the
// example self-contained the PNG is generated at run time — production
// callers usually pass `os.ReadFile` output (or any []byte source) into
// `doc.Image(...)` directly.
//
// Run from the repository root:
//
//	go run ./examples/image
//
// The output (image.pdf) carries a colored 200×200 PNG block centered
// on the page plus a paragraph caption.
package main

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"log"

	"github.com/arthurhrc/kardec"
	_ "github.com/arthurhrc/kardec/render"
)

func main() {
	logo := makeGradient(200, 200)

	doc := kardec.New(kardec.PageA4, kardec.MarginsNormal).
		Heading(1, kardec.Text("Kardec — image embedding")).
		Paragraph(
			kardec.Text("The block below is a 200x200 PNG composed at run time "),
			kardec.Text("and embedded directly into the PDF, decoded into raw RGB "),
			kardec.Text("and compressed with FlateDecode."),
		).
		Spacer(kardec.Pt(8))

	doc.Image(logo).Width(kardec.Pt(200)).Center().Build()

	doc.Spacer(kardec.Pt(8))
	doc.Paragraph(
		kardec.Text("Generated by kardec/examples/image"),
	).WithNamedStyle(kardec.StyleCaption).Align(kardec.AlignCenter)

	if err := doc.Render("image.pdf"); err != nil {
		log.Fatalf("render: %v", err)
	}
	log.Println("rendered image.pdf")
}

// makeGradient returns a width × height PNG payload whose pixels follow
// a simple two-axis gradient — visually obvious that the image really
// reaches the page rather than being a uniform fill.
func makeGradient(width, height int) []byte {
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, color.RGBA{
				R: uint8(255 * x / width),
				G: uint8(255 * y / height),
				B: 0xC0,
				A: 0xFF,
			})
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		log.Fatalf("png encode: %v", err)
	}
	return buf.Bytes()
}
