package hyphenation

// French (fr) Liang pattern subset.
//
// Curated from hyph-fr.tex (V. Lefèvre). French hyphenation is
// less regular than Spanish/Portuguese: liaison, mute-e endings,
// and the eu/au special cases produce more exceptions. This
// subset ships the open-syllable rules and the most common
// digraph exceptions; the full ~3500-pattern set extends via
// Register("fr", more).
var frPatterns = map[string]string{
	// Open syllables. French has the same consonant-leads-syllable
	// shape as Iberian languages for body text, with the
	// adjustments below.
	"ab": "a1b",
	"ac": "a1c",
	"ad": "a1d",
	"af": "a1f",
	"ag": "a1g",
	"aj": "a1j",
	"al": "a1l",
	"am": "a1m",
	"an": "a1n",
	"ap": "a1p",
	"aq": "a1q",
	"ar": "a1r",
	"as": "a1s",
	"at": "a1t",
	"av": "a1v",
	"eb": "e1b",
	"ec": "e1c",
	"ed": "e1d",
	"ef": "e1f",
	"eg": "e1g",
	"ej": "e1j",
	"el": "e1l",
	"em": "e1m",
	"en": "e1n",
	"ep": "e1p",
	"eq": "e1q",
	"er": "e1r",
	"es": "e1s",
	"et": "e1t",
	"ev": "e1v",
	"ib": "i1b",
	"ic": "i1c",
	"id": "i1d",
	"if": "i1f",
	"ig": "i1g",
	"il": "i1l",
	"im": "i1m",
	"in": "i1n",
	"ip": "i1p",
	"ir": "i1r",
	"is": "i1s",
	"it": "i1t",
	"iv": "i1v",
	"ob": "o1b",
	"oc": "o1c",
	"od": "o1d",
	"of": "o1f",
	"og": "o1g",
	"oj": "o1j",
	"ol": "o1l",
	"om": "o1m",
	"on": "o1n",
	"op": "o1p",
	"or": "o1r",
	"os": "o1s",
	"ot": "o1t",
	"ov": "o1v",
	"ub": "u1b",
	"uc": "u1c",
	"ud": "u1d",
	"uf": "u1f",
	"ug": "u1g",
	"uj": "u1j",
	"ul": "u1l",
	"um": "u1m",
	"un": "u1n",
	"up": "u1p",
	"ur": "u1r",
	"us": "u1s",
	"ut": "u1t",
	"uv": "u1v",
	// Common digraphs (single phoneme — never split).
	"ch": "2ch",
	"ph": "2ph",
	"th": "2th",
	// Doubled consonants ARE split.
	"rr": "r1r",
	"ss": "s1s",
	"ll": "l1l",
	"nn": "n1n",
	"tt": "t1t",
	"mm": "m1m",
	"pp": "p1p",
	"ff": "f1f",
	// Diphthongs — keep together.
	"ai": "a2i",
	"au": "a2u",
	"ei": "e2i",
	"eu": "e2u",
	"oi": "o2i",
	"ou": "o2u",
}
