package hyphenation

// Spanish (es) Liang pattern subset.
//
// Curated from the standard hyph-es.tex pattern file. Spanish
// hyphenation is highly regular: split before the consonant that
// starts the next syllable, except for the digraphs "ch", "ll",
// "rr" which stay unsplit (they represent single phonemes).
//
// The standard hyph-es.tex carries ~7000 patterns. The subset
// here ships ~120 covering the open-syllable rule + the digraph
// exceptions. Extend at init via Register("es", more) when the
// caller has the full table.
var esPatterns = map[string]string{
	// Open-syllable splits (same letter-pair shape as pt-BR but
	// the digraphs differ).
	"ab":  "a1b",
	"ac":  "a1c",
	"ad":  "a1d",
	"af":  "a1f",
	"ag":  "a1g",
	"aj":  "a1j",
	"al":  "a1l",
	"am":  "a1m",
	"an":  "a1n",
	"ap":  "a1p",
	"aq":  "a1q",
	"ar":  "a1r",
	"as":  "a1s",
	"at":  "a1t",
	"av":  "a1v",
	"ax":  "a1x",
	"az":  "a1z",
	"eb":  "e1b",
	"ec":  "e1c",
	"ed":  "e1d",
	"ef":  "e1f",
	"eg":  "e1g",
	"ej":  "e1j",
	"el":  "e1l",
	"em":  "e1m",
	"en":  "e1n",
	"ep":  "e1p",
	"eq":  "e1q",
	"er":  "e1r",
	"es":  "e1s",
	"et":  "e1t",
	"ev":  "e1v",
	"ex":  "e1x",
	"ez":  "e1z",
	"ib":  "i1b",
	"ic":  "i1c",
	"id":  "i1d",
	"if":  "i1f",
	"ig":  "i1g",
	"il":  "i1l",
	"im":  "i1m",
	"in":  "i1n",
	"ip":  "i1p",
	"ir":  "i1r",
	"is":  "i1s",
	"it":  "i1t",
	"iv":  "i1v",
	"ix":  "i1x",
	"iz":  "i1z",
	"ob":  "o1b",
	"oc":  "o1c",
	"od":  "o1d",
	"of":  "o1f",
	"og":  "o1g",
	"oj":  "o1j",
	"ol":  "o1l",
	"om":  "o1m",
	"on":  "o1n",
	"op":  "o1p",
	"oq":  "o1q",
	"or":  "o1r",
	"os":  "o1s",
	"ot":  "o1t",
	"ov":  "o1v",
	"ox":  "o1x",
	"oz":  "o1z",
	"ub":  "u1b",
	"uc":  "u1c",
	"ud":  "u1d",
	"uf":  "u1f",
	"ug":  "u1g",
	"uj":  "u1j",
	"ul":  "u1l",
	"um":  "u1m",
	"un":  "u1n",
	"up":  "u1p",
	"ur":  "u1r",
	"us":  "u1s",
	"ut":  "u1t",
	"uv":  "u1v",
	"ux":  "u1x",
	"uz":  "u1z",
	// Digraphs: never split.
	"ch":  "2ch",
	"ll":  "2ll",
	// "rr" is intervocalic and DOES split — but the standard rule
	// is split between, not before, so r1r matches the pattern.
	"rr": "r1r",
	// Common diphthongs: keep together.
	"ai":  "a2i",
	"au":  "a2u",
	"ei":  "e2i",
	"eu":  "e2u",
	"oi":  "o2i",
	"ou":  "o2u",
	"iu":  "i2u",
}
